cpp_quote("/********************************************************************")
cpp_quote("*	Module:			filesign.h")
cpp_quote("*	Process ID:")
cpp_quote("*	S/W Platforms:")
cpp_quote("*	H/W Platforms:")
cpp_quote("*	Compiler:")
cpp_quote("*	Description: 	Definion of EMSFILESIGNATURE                     ")
cpp_quote("*")
cpp_quote("*	Usage:")
cpp_quote("*	Entry Point:")
cpp_quote("*	Input Files:")
cpp_quote("*	Output Files:")
cpp_quote("*	Comments:")
cpp_quote("*")
cpp_quote("*********************************************************************")
cpp_quote("*	              Copyright (c) 2002 by EMS Technologies, Inc.,")
cpp_quote("*										All rights reserved")
cpp_quote("*	This program is unpublished software and contains the trade secrets")
cpp_quote("*	and confidential information of EMS Technologies, Inc.  It may not be ")
cpp_quote("* reproduced in whole or in part, in any form or by any means whatsoever ")
cpp_quote("* without the express written permission of EMS Technologies, Inc.")
cpp_quote("*")
cpp_quote("********************************************************************/")
cpp_quote("")
cpp_quote("/*******************************************************************")
cpp_quote("")
cpp_quote("  Revision Record")
cpp_quote("")
cpp_quote("	Rev	Date			Auth	Changes")
cpp_quote("	===	====			====	=======")
cpp_quote("")
cpp_quote("	0.0	02/11/2		rvw	start")
cpp_quote("")
cpp_quote("********************************************************************/")
cpp_quote("#ifndef INC_FILESIGN")
cpp_quote("#define INC_FILESIGN")

import "unknwn.idl";
import "emstypex.idl";

cpp_quote("")
cpp_quote("")

#define _EMS_RPC_VERSION 1
#define __RPC_FAR 

[
	uuid(FCC64EBD-EAE6-4419-B569-B3707F66DD90),
	helpstring("IEMSFILESIGNATURE"),
	pointer_default(unique)
]

interface IEMSFILESIGNATURE
{
#pragma pack(1)

typedef struct _tagEMSFILESIGNATURE
{
	BYTE				cEMS[3];
	BYTE				cType[5];
	union
	{
		WORD 			wNumber;
		struct 		
		{
			BYTE		cMinor;
			BYTE		cMajor;
		} number;
	} version;
} EMSFILESIGNATURE, *LPEMSFILESIGNATURE;

typedef struct _tagEMSCAPTUREFILESIGNATURE
{
	EMSFILESIGNATURE		sig;	// "EMScaptr" 1.0
	INT						nChannel;
	INT						nRecLength;
} EMSCAPTUREFILESIGNATURE, *LPEMSCAPTUREFILESIGNATURE;

typedef struct _tagEMSCHANNELSIGNATURE
{
	union
	{
		WORD 			wNumber;
		struct 		
		{
			BYTE		cMinor;
			BYTE		cMajor;
		} number;
	} version;
	WORD						wChannel;
	INT						nRecLength;
} EMSCHANNELSIGNATURE, *LPEMSCHANNELSIGNATURE;


#pragma pack()
}

cpp_quote("#endif // INC_FILESIGN")









