#ifndef __MOA_CONTROLLER_DEF_H__
#define __MOA_CONTROLLER_DEF_H__

typedef enum _EMS_SAT_AGCHOLD 
{
	EMS_SAT_AGCHOLD_UNKNOWN  = 0,
	EMS_SAT_AGCHOLD_ON       = 1,
	EMS_SAT_AGCHOLD_OFF      = 2
} EMS_SAT_AGCHOLD;

typedef enum _EMS_SAT_POLARIZATION 
{
	EMS_SAT_POLAR_UNKNOWN  = 0,
	EMS_SAT_POLAR_RHCP	   = 1,
	EMS_SAT_POLAR_LHCP     = 2
} EMS_SAT_POLARIZATION;

typedef enum _EMS_SAT_FREQ_BAND 
{
	EMS_SAT_FREQ_BAND_UNKNOWN  = 0,
	EMS_SAT_S_BAND_GPS_POC	   = 1,
	EMS_SAT_L_BAND_GALILEO	   = 2,
	EMS_SAT_L_BAND_GEOS_SARSAT = 3,
	EMS_SAT_L_BAND_GPS_GLONASS = 4
} EMS_SAT_FREQ_BAND;


#endif