cpp_quote("// {56628AF1-97FC-11d5-8C04-009027912866}")
cpp_quote("DEFINE_GUID( IID_IEMSWidebandStatus, 0x56628af1, 0x97fc, 0x11d5, 0x8c, 0x4, 0x0, 0x90, 0x27, 0x91, 0x28, 0x66);")
cpp_quote(" " )

import "unknwn.idl";
import "emstypex.idl";
import "emstatus.idl";

#define _EMS_RPC_VERSION 1
#define __RPC_FAR 

[
	object, uuid(56628AF1-97FC-11d5-8C04-009027912866),
	helpstring("IEMSWidebandStatus Interface"),
	pointer_default(unique)
]

interface IEMSWidebandStatus : IEMSStatus
{
#pragma pack(1)

	typedef struct _tagEMSWIDEBANDINFO
	{
    WORD  wWidebandStatus;       // SARWideband device status
	
		WORD wSarpTotalFrames;
		WORD wSarpTotalMessages;
		WORD wSarpTotalSyncLosses;
		WORD wSarpTotalNoSyncs;
		WORD wSarpCurrentSyncLosses;
		WORD wSarpCurrentNoSyncs;

		WORD wSarrTotalMessages;

		WORD wCBC121Counts;
		WORD wCBC243Counts;
		WORD wCBC406Counts;
		
// GEO
		WORD  wNumGroup;              // Number of  active Groups (in message integration)
		WORD  wNumActive;             // Number of active beacons (confirmed in message integration)
		WORD  wNumActiveDistress;     // Number of active distress only beacons (confirmed in message integration)
		WORD  wNumDistressMsg;        // Total number of distress only messages since last update
		WORD  wNumMsg;                // Total number of messages since last update
		WORD  wNumDet;                // Total number of detections since last update
		EMSTIME        LastTimeDetect;        // Time of last beacon detection
		EMSTIME        LastRefBcnTimeDetect;  // Time of last reference beacon detection
	} EMSWIDEBANDINFO, *LPEMSWIDEBANDINFO;

#pragma pack()

	HRESULT ResetWidebandInfo( void );

	HRESULT SetWidebandInfo( [in] EMSWIDEBANDINFO *lpInfo );
	HRESULT GetWidebandInfo( [out] EMSWIDEBANDINFO *lpInfo );
};

typedef [unique] IEMSWidebandStatus *LPEMSWIDEBANDSTATUS;
