/*********************************************************************
*	              Copyright (c) 2006 by EMS Technologies, Inc.,
*										All rights reserved
*	This program is unpublished software and contains the trade secrets
*	and confidential information of EMS Technologies, Inc.  It may not be 
* reproduced in whole or in part, in any form or by any means whatsoever 
* without the express written permission of EMS Technologies, Inc.
*
********************************************************************/

/*******************************************************************

  Revision Record

	$Log:
	$
********************************************************************/

#include "soapclientfaultprocessor.h"
#include "generalmsgs.h"
#include "emsexcpt.h"
#include "convutility.h"

//********* These structures are normally auto-generated by the gSOAP compiler and written into the soapstub.h file.
// Only when a custom structure is used would they be different than the default.  So, add the definitions here.  Define the
// symbol, EMS_USE_SOAP_FAULT_DEFS to enable.

#ifdef EMS_USE_SOAP_FAULT_DEFS

/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};

/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};

/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};

/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};

#else

#include "soapstub.h"

#endif
//*********

CEMSSOAPClientFaultProcessor::CEMSSOAPClientFaultProcessor()
{
}

CEMSSOAPClientFaultProcessor::~CEMSSOAPClientFaultProcessor()
{
}

void 
CEMSSOAPClientFaultProcessor::HandleSoapError( struct soap* pSoap )
{
	if( pSoap )
	{
		CEMSLogMsgParam oParam;

		if (pSoap->version == 2) // SOAP 1.2 is used 
		{
			oParam.AddString( CEMSConversionUtil::ConvertToString( pSoap->fault->SOAP_ENV__Code->SOAP_ENV__Value ).c_str() );
			oParam.AddString( CEMSConversionUtil::ConvertToString( pSoap->fault->SOAP_ENV__Reason->SOAP_ENV__Text ).c_str() );

			if( pSoap->fault->detail->__any )
			{
				oParam.AddString( CEMSConversionUtil::ConvertToString( pSoap->fault->detail->__any ).c_str() );
			}
			else
			{
				oParam.AddString(L"N\\A" );
			}
		} 
		else 
		{ 
			oParam.AddString( CEMSConversionUtil::ConvertToString( pSoap->fault->faultcode ).c_str() );
			oParam.AddString( CEMSConversionUtil::ConvertToString( pSoap->fault->faultstring ).c_str() );

			if( pSoap->fault->detail )
			{
				if( pSoap->fault->detail->__any )
					oParam.AddString( CEMSConversionUtil::ConvertToString( pSoap->fault->detail->__any ).c_str() );
				else
					oParam.AddString(L"N\\A" );
			}
			else
			{
				oParam.AddString(L"N\\A" );
			}
		} 

		throw CEMSException( EMS_SOAP_CALL_ERROR, oParam );

	}
}

void 
CEMSSOAPClientFaultProcessor::HandleSoapError( const int ciRetCode  )
{
	CEMSLogMsgParam oParam;
	oParam.Add( (ULONG) ciRetCode );

	throw CEMSException( EMS_SOAP_FRAMEWORK_ERROR, oParam );
}